# Generated by Django 2.0.7 on 2018-07-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.PositiveSmallIntegerField(max_length=20)),
                ('Pid', models.PositiveSmallIntegerField(max_length=20)),
                ('name', models.CharField(default='', max_length=50)),
                ('score', models.IntegerField(max_length=11)),
                ('is_upload_only', models.SmallIntegerField(default=0, max_length=1)),
                ('c_time_limit', models.PositiveIntegerField(default=500, max_length=11)),
                ('python_time_limit', models.PositiveIntegerField(default=1500, max_length=11)),
                ('java_time_limit', models.PositiveIntegerField(default=2000, max_length=11)),
                ('memory_limit', models.PositiveIntegerField(default=50000, max_length=11)),
                ('allowed_languages', models.TextField(default='')),
                ('diff_cmd', models.CharField(default='diff', max_length=20)),
                ('diff_arg', models.CharField(default='-bB', max_length=20)),
            ],
        ),
    ]
